### ISSUE TITLE
void is not a class element

### ISSUE THREAD

**Issue by tbm98** [Milad-Akarie/injectable#229]
command: `flutter pub run build_runner build --delete-conflicting-outputs --verbose`

error: 
```
[  +83 ms] executing: sysctl hw.optional.arm64
[  +14 ms] Exit code 1 from: sysctl hw.optional.arm64
[        ] sysctl: unknown oid 'hw.optional.arm64'
[   +6 ms] executing: [/Users/minhtran/fvm/versions/stable/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +36 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] f4abaa0735eba4dfd8f33f73363911d63931fe03
[   +1 ms] executing: [/Users/minhtran/fvm/versions/stable/] git tag --points-at f4abaa0735eba4dfd8f33f73363911d63931fe03
[  +41 ms] Exit code 0 from: git tag --points-at f4abaa0735eba4dfd8f33f73363911d63931fe03
[        ] 2.2.3
[   +6 ms] executing: [/Users/minhtran/fvm/versions/stable/] git rev-parse --abbrev-ref --symbolic @{u}
[  +45 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/Users/minhtran/fvm/versions/stable/] git ls-remote --get-url origin
[  +36 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +161 ms] executing: [/Users/minhtran/fvm/versions/stable/] git rev-parse --abbrev-ref HEAD
[  +35 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[   +7 ms] executing: sw_vers -productName
[  +17 ms] Exit code 0 from: sw_vers -productName
[        ] macOS
[        ] executing: sw_vers -productVersion
[  +18 ms] Exit code 0 from: sw_vers -productVersion
[        ] 11.4
[        ] executing: sw_vers -buildVersion
[  +19 ms] Exit code 0 from: sw_vers -buildVersion
[        ] 20F71
[  +89 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +38 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[  +33 ms] executing: /Users/minhtran/fvm/versions/stable/bin/cache/dart-sdk/bin/pub run build_runner build --delete-conflicting-outputs --verbose
[INFO] Entrypoint:Generating build script...
[INFO] Entrypoint:Generating build script completed, took 1.1s

[INFO] BuildDefinition:Initializing inputs
[INFO] BuildDefinition:Reading cached asset graph...
[INFO] BuildDefinition:Reading cached asset graph completed, took 863ms

[INFO] BuildDefinition:Checking for updates since last build...
[INFO] BuildDefinition:Checking for updates since last build completed, took 1.6s

[INFO] Build:Running build...
[INFO] Build:Running build completed, took 73ms

[INFO] Build:Caching finalized dependency graph...
[INFO] Build:Caching finalized dependency graph completed, took 471ms

[SEVERE] injectable_generator:injectable_builder on lib/enviroments.dart (cached):

void is not a class element
package:injectable_generator/utils.dart 38:5                             throwIf
package:injectable_generator/resolvers/dependency_resolver.dart 59:5     DependencyResolver.resolveModuleMember
package:injectable_generator/generators/injectable_generator.dart 51:15  InjectableGenerator.generate
package:source_gen/src/builder.dart 328:23                               _generate

[SEVERE] Build:
Failed after 601ms
[+8975 ms] "flutter run" took 9,066ms.
[   +5 ms] pub finished with exit code 1
[   +1 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      _DefaultPub.interactively (package:flutter_tools/src/dart/pub.dart:368:7)
           <asynchronous suspension>
           #2      PackagesForwardCommand.runCommand (package:flutter_tools/src/commands/packages.dart:241:5)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1043:27)
           <asynchronous suspension>
           #4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #5      CommandRunner.runCommand (package:args/command_runner.dart:196:13)
           <asynchronous suspension>
           #6      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:284:9)
           <asynchronous suspension>
           #7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #8      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:232:5)
           <asynchronous suspension>
           #9      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #11     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>
           
           
[ +220 ms] ensureAnalyticsSent: 191ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1

```

environments.dart
```dart
import 'dart:io';

import 'package:injectable/injectable.dart';

import 'base/firebase_manager/firebase_const.dart';

@module
abstract class Env {
  String? appTitle;
  String? baseUrl;
  String? fbProjectId;

  String? fbApiKey;
  String? fbAppId;
  String? fbSenderId;
}

class DevEnv implements Env {
  @override
  String? appTitle = "Dev";

  @override
  String? baseUrl = "";

  @override
  String? fbProjectId = FBNonProdConst.my_projectId;

  @override
  String? fbApiKey = Platform.isIOS
      ? FBNonProdConst.ios_my_apiKey
      : FBNonProdConst.android_my_apiKey;

  @override
  String? fbAppId = Platform.isIOS
      ? FBNonProdConst.ios_my_appId
      : FBNonProdConst.android_my_appId;

  @override
  String? fbSenderId = Platform.isIOS
      ? FBNonProdConst.ios_my_messagingSenderId
      : FBNonProdConst.android_my_messagingSenderId;
}

class QCEnv implements Env {
  @override
  String? appTitle = "QC";
  @override
  String? baseUrl = "";

  @override
  String? fbProjectId = FBNonProdConst.my_projectId;

  @override
  String? fbApiKey = Platform.isIOS
      ? FBNonProdConst.ios_my_apiKey
      : FBNonProdConst.android_my_apiKey;

  @override
  String? fbAppId = Platform.isIOS
      ? FBNonProdConst.ios_my_appId
      : FBNonProdConst.android_my_appId;

  @override
  String? fbSenderId = Platform.isIOS
      ? FBNonProdConst.ios_my_messagingSenderId
      : FBNonProdConst.android_my_messagingSenderId;
}

class UATEnv implements Env {
  @override
  String? appTitle = "UAT";
  @override
  String? baseUrl = "";

  @override
  String? fbProjectId = FBNonProdConst.my_projectId;

  @override
  String? fbApiKey = Platform.isIOS
      ? FBNonProdConst.ios_my_apiKey
      : FBNonProdConst.android_my_apiKey;

  @override
  String? fbAppId = Platform.isIOS
      ? FBNonProdConst.ios_my_appId
      : FBNonProdConst.android_my_appId;

  @override
  String? fbSenderId = Platform.isIOS
      ? FBNonProdConst.ios_my_messagingSenderId
      : FBNonProdConst.android_my_messagingSenderId;
}

class ProdEnv implements Env {
  @override
  String? appTitle = "Prod";
  @override
  String? baseUrl = "";

  @override
  String? fbProjectId = FBProdConst.my_projectId;

  @override
  String? fbApiKey = Platform.isIOS
      ? FBProdConst.ios_my_apiKey
      : FBProdConst.android_my_apiKey;

  @override
  String? fbAppId =
      Platform.isIOS ? FBProdConst.ios_my_appId : FBProdConst.android_my_appId;

  @override
  String? fbSenderId = Platform.isIOS
      ? FBProdConst.ios_my_messagingSenderId
      : FBProdConst.android_my_messagingSenderId;
}

Env getEnvironment() {
  switch (FlavorConfig.instance?.flavor) {
    case Flavor.DEV:
      return DevEnv();
    case Flavor.PROD:
      return ProdEnv();
    case Flavor.QC:
      return QCEnv();
    case Flavor.UAT:
      return UATEnv();
    default:
      throw Exception('Env not implemented yet');
  }
}
```

**Comment by Milad-Akarie** [comment]
You're registering multiple unnamed instance of the same type [String] ( not sure if it's the root issue)

This's how I usually register my env vars

```dart
abstract class Env{
  String get baseUrl;
  String get apiKey;
}

@dev
@Singleton(as: Env)
class DevEnv extends Env{
  @override
  String get baseUrl;
  @override
  String get apiKey;
}

@prod
@Singleton(as: Env)
class ProdEnv extends Env{
  @override
  String get baseUrl;
  @override
  String get apiKey;
}

```
hope this helps

**Comment by tbm98** [comment]
I've tried it and got another issue
```
Injectable Generator ---------------------------------------------------
DevEnv [Env] env: [dev] 
is registered more than once under the same environment
------------------------------------------------------------------------ 
```

**Comment by tbm98** [comment]
and I also have some environments like QC, UAT. what annotation should I use for them?

**Comment by Milad-Akarie** [comment]
Please show me your injecteble classes

**Comment by tbm98** [comment]
here it is
```dart
import 'dart:io';

import 'package:injectable/injectable.dart';
import 'package:merchant_app_common/merchant_app_common.dart';

import 'base/firebase_manager/firebase_const.dart';


abstract class Env {
  String? appTitle;
  String? baseUrl;
  String? fbProjectId;

  String? fbApiKey;
  String? fbAppId;
  String? fbSenderId;
}

@dev
@Singleton(as: Env)
class DevEnv implements Env {
  @override
  String? appTitle = "";

  @override
  String? baseUrl = "";

  @override
  String? fbProjectId = FBNonProdConst.my_projectId;

  @override
  String? fbApiKey = Platform.isIOS
      ? FBNonProdConst.ios_my_apiKey
      : FBNonProdConst.android_my_apiKey;

  @override
  String? fbAppId = Platform.isIOS
      ? FBNonProdConst.ios_my_appId
      : FBNonProdConst.android_my_appId;

  @override
  String? fbSenderId = Platform.isIOS
      ? FBNonProdConst.ios_my_messagingSenderId
      : FBNonProdConst.android_my_messagingSenderId;
}


class QCEnv implements Env {
  @override
  String? appTitle = "";
  @override
  String? baseUrl = "";

  @override
  String? fbProjectId = FBNonProdConst.my_projectId;

  @override
  String? fbApiKey = Platform.isIOS
      ? FBNonProdConst.ios_my_apiKey
      : FBNonProdConst.android_my_apiKey;

  @override
  String? fbAppId = Platform.isIOS
      ? FBNonProdConst.ios_my_appId
      : FBNonProdConst.android_my_appId;

  @override
  String? fbSenderId = Platform.isIOS
      ? FBNonProdConst.ios_my_messagingSenderId
      : FBNonProdConst.android_my_messagingSenderId;
}
class UATEnv implements Env {
  @override
  String? appTitle = "";
  @override
  String? baseUrl = "";

  @override
  String? fbProjectId = FBNonProdConst.my_projectId;

  @override
  String? fbApiKey = Platform.isIOS
      ? FBNonProdConst.ios_my_apiKey
      : FBNonProdConst.android_my_apiKey;

  @override
  String? fbAppId = Platform.isIOS
      ? FBNonProdConst.ios_my_appId
      : FBNonProdConst.android_my_appId;

  @override
  String? fbSenderId = Platform.isIOS
      ? FBNonProdConst.ios_my_messagingSenderId
      : FBNonProdConst.android_my_messagingSenderId;
}

@prod
@Singleton(as: Env)
class ProdEnv implements Env {
  @override
  String? appTitle = "";
  @override
  String? baseUrl = "";

  @override
  String? fbProjectId = FBProdConst.my_projectId;

  @override
  String? fbApiKey = Platform.isIOS
      ? FBProdConst.ios_my_apiKey
      : FBProdConst.android_my_apiKey;

  @override
  String? fbAppId =
      Platform.isIOS ? FBProdConst.ios_my_appId : FBProdConst.android_my_appId;

  @override
  String? fbSenderId = Platform.isIOS
      ? FBProdConst.ios_my_messagingSenderId
      : FBProdConst.android_my_messagingSenderId;
}

Env getEnvironment() {
  switch (FlavorConfig.instance?.flavor) {
    case Flavor.DEV:
      return DevEnv();
    case Flavor.PROD:
      return ProdEnv();
    case Flavor.QC:
      return QCEnv();
    case Flavor.UAT:
      return UATEnv();
    default:
      throw Exception('Env not implemented yet');
  }
}

```
