### ISSUE TITLE
[injectable_generator] Wrong initialization order in singleton modules with dependencies

### ISSUE THREAD

**Issue by proninyaroslav** [Milad-Akarie/injectable#238]
Tested on `injectable_generator` `1.4.1` and `1.5.0`.

Let's say we have a code like this:
```Dart
final GetIt getIt = GetIt.instance;

@injectableInit
Future<void> initInjector() async {
  $initGetIt(getIt, environment: Environment.prod);
  await getIt.allReady();
}

Future<void> main() async {
  await initInjector();
  getIt<First>();
  ...
}

@singleton
class First {
  final Second second;

  First(this.second);
}

class Second {
  final String? value;

  Second(this.value);

  Second.test() : value = null;
}

@injectable
class Third {
  String get value => 'value';
}

@module
abstract class SecondModule {
  @Singleton(env: [Environment.prod, Environment.dev])
  Second main(Third third) => Second(third.value);

  @Singleton(env: [Environment.test])
  Second test() => Second.test();
}
```
In the `SecondModule.main()` method we pass the injectable object of the class `Third`, and in the `SecondModule.test()` method we don't  pass anything. `SecondModule` is used to inject in the `First` class.

If we run this example, we get the exception:

<details>
  <summary>Crash log</summary>

```
E/flutter ( 9503): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: 'package:get_it/get_it_impl.dart': Failed assertion: line 372 pos 7: 'instanceFactory != null': Object/factory with  type Second is not registered inside GetIt.
E/flutter ( 9503): (Did you accidentally do GetIt sl=GetIt.instance(); instead of GetIt sl=GetIt.instance;
E/flutter ( 9503): Did you forget to register it?)
E/flutter ( 9503): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39)
E/flutter ( 9503): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
E/flutter ( 9503): #2      _GetItImplementation._findFactoryByNameAndType
E/flutter ( 9503): #3      _GetItImplementation.get
E/flutter ( 9503): #4      _GetItImplementation.call
E/flutter ( 9503): #5      $initGetIt
E/flutter ( 9503): #6      initInjector
E/flutter ( 9503): #7      main
E/flutter ( 9503): #8      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:142:25)
E/flutter ( 9503): #9      _rootRun (dart:async/zone.dart:1354:13)
E/flutter ( 9503): #10     _CustomZone.run (dart:async/zone.dart:1258:19)
E/flutter ( 9503): #11     _runZoned (dart:async/zone.dart:1789:10)
E/flutter ( 9503): #12     runZonedGuarded (dart:async/zone.dart:1777:12)
E/flutter ( 9503): #13     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:138:5)
E/flutter ( 9503): #14     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:283:19)
E/flutter ( 9503): #15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```

</details>

Let's take a look at the generated code:
```Dart
final secondModule = _$SecondModule();
gh.factory<_i3.Third>(() => _i3.Third());
gh.singleton<_i3.Second>(secondModule.test(), registerFor: {_test});
gh.singleton<_i3.First>(_i3.First(get<_i3.Second>()));
// Registers after registering First, 
// which throws an error during registering First 
gh.singleton<_i3.Second>(secondModule.main(get<_i3.Third>()),
    registerFor: {_prod, _dev});
```

The problem is that the `dev` and `prod` versions of the `Second` class are registered after the registration of the` First` class, so an exception is thrown, if during initialization we specify `prod` or `dev`.

The solution at the moment is to add the `Third` argument to the `SecondModule.test()` method:
```Dart
@module
abstract class SecondModule {
  @Singleton(env: [Environment.prod, Environment.dev])
  Second main(Third third) => Second(third.value);

  @Singleton(env: [Environment.test])
  // `third` is not used, but it is needed for correct registration
  Second test(Third third) => Second.test();
}
```

In this case, the plugin generates the correct code:
```Dart
final secondModule = _$SecondModule();
gh.factory<_i3.Third>(() => _i3.Third());
// Correct registration sequence
gh.singleton<_i3.Second>(secondModule.main(get<_i3.Third>()),
    registerFor: {_prod, _dev}); 
gh.singleton<_i3.Second>(secondModule.test(get<_i3.Third>()),
    registerFor: {_test});
gh.singleton<_i3.First>(_i3.First(get<_i3.Second>()));
```

**Comment by Milad-Akarie** [comment]
@proninyaroslav This issue has to do with environments, the sorting logic didn't pay attention to environment keys before but that should be fixed in `injectable_generator 1.5.1`
please reopen if it's not.
